url: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
subdirectory: deployment/sriov-network-operator-chart
commit: 689d7eddd443c56bb04d1ff3c06c65661172082a # tag: v1.3.0
packageVersion: 1
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
