url: oci://ghcr.io/k8snetworkplumbingwg/sriov-network-operator-chart:1.5.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
